### ISSUE TITLE
Normal / Displacement Maps

### ISSUE THREAD

**Issue by SamuelTallet** [MilchRatchet/Luminary#67]
Hello,

First, bravo for your excellent work!

It would be great Luminary supports Normal and Displacement maps.

Since they are complementary, I suggest to pack them in same image:

- Geometry Textures
    - Red: Normal X
    - Green: Normal Y
    - Blue: Normal Z
    - Alpha: Displacement

In the `*.mtl` file, this image could be referenced with the `norm_disp` keyword.

**Comment by MilchRatchet** [comment]
Good idea. The issue is that shading normal and geometric normal differences already cause a lot of issues. So while normal maps will surely be a good addition they will also cause a lot of headaches. However, as far as I know there are some papers out there tackling this issue.

This is surely something that I could add in the far future.

**Comment by SamuelTallet** [comment]
Good luck!
